version: "3.9"
services:
  server:
    hostname: localhost
#    network_mode: host
    build:
      context: ./docker
      dockerfile: postgres_server
    ports:
      - "5432:5432"
  pga:
    build:
      context: ./docker
      dockerfile: postgres_pga
    depends_on:
      - server
#    network_mode: host
    ports:
      - "5433:80"
  application:
#    network_mode: host
    build:
      context: ./docker
      dockerfile: application
    depends_on:
      - server
    ports:
      - "8082:8082"